#!/bin/bash

command="composer install && php artisan setup"

echo "$command"
docker exec -it laravel-app bash -c "sudo -u devuser /bin/bash -c \"$command\""

echo "==========================================="
echo "Running php unit tests............"
./phpunit
